### ISSUE TITLE
管理者が出荷指示をする際の出荷案内が自動で作成出来るようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [DecodeLLC/seiren-web#30]

**Comment by alexeypolitov** [comment]
> 出荷案内が自動で作成出来る
@tsubasamatsumoto こちらはどういう意味ですか？

**Comment by tsubasamatsumoto** [comment]
![image](https://user-images.githubusercontent.com/19566850/31644146-863d6146-b32f-11e7-83bd-ab3cda9e9296.png)

**Comment by tsubasamatsumoto** [comment]
管理者が出荷の指示をWEBでしたときに、その内容一覧がでるようにしてほしい。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto #24 と同じタスクに見えますがいかがですか？

**Comment by tsubasamatsumoto** [comment]
＃24と同じです。すみません。
