### ISSUE TITLE
ロット作成、検査データの修正がWEB画面でも出来るようにしてください

### ISSUE THREAD

**Issue by tsubasamatsumoto** [DecodeLLC/seiren-web#32]

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto そうするとフローは壊れる可能性があります。アプリだと順番で生産段階が動いてますがウェブでそういう作業はする予定なかったはずです。

**Comment by tsubasamatsumoto** [comment]
出荷前まではウェブで修正できるようにお願いします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto ランキング、加工品番、加工区分、欠点のみ変更できるようにします。それでよろしいですか？

**Comment by tsubasamatsumoto** [comment]
ロールの詳細を開いた時の基本情報以外は変えれるようにしたいです。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 精錬情報はすでに変更可能です。検査情報は変更できるようにします。出荷は変更なしでいいですか？

**Comment by tsubasamatsumoto** [comment]
出荷も変更できるようお願いします。台車からロールを載せ替えたときの対策です。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 変更できるようにしました

**Comment by tsubasamatsumoto** [comment]
OK
