### ISSUE TITLE
品番ごとに設定データを登録できるようにしてください。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [DecodeLLC/seiren-web#34]
週報、月報用に使うデータとして
①原糸代
②織り工賃
③精錬賃
④製品の疋長

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto こちらのデータは週報、月報のみで使う予定ですか？あと、項目ごとにデータのサンプルをください

**Comment by tsubasamatsumoto** [comment]
はい、週報・月報で使うデータです。サンプルは準備してアップします。

**Comment by tsubasamatsumoto** [comment]
[日報、月報で使用するデータ.xlsx](https://github.com/DecodeLLC/seiren-web/files/1390847/default.xlsx)

**Comment by tsubasamatsumoto** [comment]
単価は織工賃＋原糸代＋精錬賃で計算。
単価✕疋数✕１疋長＝金額を計算。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto データを登録できるようにしました

**Comment by tsubasamatsumoto** [comment]
データの削除が出来ないバグについて修正お願いします。

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。プライベートモードでご確認ください

**Comment by tsubasamatsumoto** [comment]
OK
